### ISSUE TITLE
Is this open source?

### ISSUE THREAD

**Issue by berndca** [olofk/stream_utils#1]
I was hoping to be able to use this project along with its dependencies and I'm wondering if it is open source. If it is, could you please specify a license?

Thanks, Bernd

**Comment by olofk** [comment]
Yes, they are open source, but I've not been very good with stating licenses of my own code. I have now added an MIT license file to the repository. Will add for the dependencies as well, but you can consider them all MIT and add license headers to the individual files when I can find the time

**Comment by olofk** [comment]
Actually, I've changed to th (functionally equivalent) ISC license instead as I've used that elsewhere for my RTL code
